/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#506249',
        'surface-bright': '#2c2c2c',
        'inverse-primary': '#52644b',
        'on-tertiary-fixed': '#014500',
        'primary-fixed': '#dcf1d1',
        'secondary-fixed': '#ffc974',
        'secondary-container': '#7f5600',
        'outline-variant': '#484848',
        'outline': '#767575',
        'surface-dim': '#0e0e0e',
        'secondary-fixed-dim': '#ffb630',
        'secondary-dim': '#eba200',
        'primary-container': '#93a689',
        'on-surface': '#ffffff',
        'surface': '#0e0e0e',
        'tertiary-fixed-dim': '#01ed00',
        'surface-container-high': '#202020',
        'surface-tint': '#e8fddc',
        'on-background': '#ffffff',
        'surface-container-low': '#131313',
        'on-secondary-container': '#fff6ef',
        'tertiary-dim': '#01ed00',
        'tertiary-fixed': '#00fd00',
        'error': '#ff7351',
        'on-secondary-fixed': '#482f00',
        'on-secondary-fixed-variant': '#6d4a00',
        'surface-container': '#191a1a',
        'surface-variant': '#262626',
        'tertiary-container': '#00fd00',
        'on-primary-fixed-variant': '#54664c',
        'on-tertiary-fixed-variant': '#026500',
        'inverse-on-surface': '#565555',
        'on-secondary': '#513500',
        'secondary': '#fdaf00',
        'on-primary-fixed': '#384932',
        'primary-dim': '#daeece',
        'inverse-surface': '#fcf9f8',
        'error-dim': '#d53d18',
        'surface-container-highest': '#262626',
        'on-error-container': '#ffd2c8',
        'background': '#0e0e0e',
        'error-container': '#b92902',
        'on-error': '#450900',
        'on-tertiary-container': '#015a00',
        'surface-container-lowest': '#000000',
        'primary-fixed-dim': '#cee3c3',
        'on-surface-variant': '#adaaaa',
        'tertiary': '#9fff88',
        'primary': '#e8fddc',
        'on-primary-container': '#172712',
        'on-tertiary': '#026400',
        accent: '#00ff00',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Space Grotesk', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        sans: ['Space Grotesk', 'sans-serif'],
        mono: ['Space Grotesk', 'monospace'],
      },
      borderRadius: {
        'none': '0px',
        'DEFAULT': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        'full': '9999px',
      },
      boxShadow: {
        'luminous': '0px 0px 15px rgba(0, 255, 0, 0.1)',
        'sunken': 'inset 0px 2px 10px rgba(0, 0, 0, 0.8)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};