import React, { useState, useRef, useEffect } from 'react';

const AITerminal = () => {
  const [output, setOutput] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [history, setHistory] = useState([]);
  const [historyIndex, setHistoryIndex] = useState(-1); // -1 means current input
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamingInterval, setStreamingInterval] = useState(null);
  const [sidePanelOpen, setSidePanelOpen] = useState(false);
  const outputRef = useRef(null);

  // Mock command handler
  const handleCommand = (command) => {
    const [cmd, ...args] = command.trim().split(' ');
    const argString = args.join(' ');
    
    switch (cmd) {
      case 'help':
        return `Available commands:
  /help - Show this help message
  /run <command> - Simulate running a command
  /explain <topic> - Explain a topic
  `;
      case 'run':
        return `Running: ${argString}\nResult: Success!`;
      case 'explain':
        return `Explanation of ${argString}:\nThis is a mock explanation. In a real app, this would be generated by the AI.`;
      default:
        return `Unknown command: ${cmd}. Type /help for available commands.`;
    }
  };

  // Add a line to output
  const addLine = (line) => {
    setOutput(prev => [...prev, line]);
  };

  // Start streaming effect for a response
  const startStreaming = (fullResponse) => {
    setIsStreaming(true);
    addLine({ type: 'streaming', content: '' });
    
    let charIndex = 0;
    const interval = setInterval(() => {
      if (charIndex < fullResponse.length) {
        setOutput(prev => {
          const newOutput = [...prev];
          newOutput[newOutput.length - 1] = { 
            type: 'streaming', 
            content: newOutput[newOutput.length - 1].content + fullResponse[charIndex] 
          };
          return newOutput;
        });
        charIndex++;
      } else {
        clearInterval(interval);
        setIsStreaming(false);
        // Convert streaming line to regular output
        setOutput(prev => {
          const newOutput = [...prev];
          newOutput[newOutput.length - 1] = { 
            type: 'output', 
            content: newOutput[newOutput.length - 1].content 
          };
          return newOutput;
        });
      }
    }, 20); // 20ms per character for typing effect
    
    setStreamingInterval(interval);
  };

  // Handle input changes
  const handleInputChange = (e) => {
    const value = e.target.value;
    setInputValue(value);
    setHistoryIndex(-1); // Reset history navigation when typing
  };

  // Handle key down events
  const handleKeyDown = (e) => {
    if (isStreaming) return; // Ignore input during streaming

    if (e.key === 'Enter') {
      e.preventDefault();
      if (inputValue.trim() === '') return;
      
      // Add input line to output
      addLine({ type: 'input', content: inputValue });
      
      // Add to history (chronological order: oldest first)
      setHistory(prev => [...prev, inputValue]);
      setHistoryIndex(-1); // Reset history index
      
      // Clear input
      setInputValue('');
      
      // Process command
      const command = inputValue.trim();
      if (command.startsWith('/')) {
        const response = handleCommand(command.substring(1));
        startStreaming(response);
      } else {
        // Mock AI response for non-command input
        startStreaming(`You said: "${command}"\nAI: I'm a mock AI. I only respond to commands. Type /help for help.`);
      }
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (history.length === 0) return;
      
      if (historyIndex < history.length - 1) {
        const newIndex = historyIndex + 1;
        setHistoryIndex(newIndex);
        setInputValue(history[newIndex]);
      } else if (historyIndex === -1 && history.length > 0) {
        // Show latest history when at current input
        setHistoryIndex(history.length - 1);
        setInputValue(history[history.length - 1]);
      }
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (historyIndex >= 0) {
        const newIndex = historyIndex - 1;
        if (newIndex >= 0) {
          setHistoryIndex(newIndex);
          setInputValue(history[newIndex]);
        } else {
          setHistoryIndex(-1);
          setInputValue('');
        }
      }
    } else if (e.key === 'Escape') {
      e.preventDefault();
      setInputValue('');
      setHistoryIndex(-1);
    }
  };

  // Scroll to bottom when output changes
  useEffect(() => {
    if (outputRef.current) {
      outputRef.current.scrollTop = outputRef.current.scrollHeight;
    }
  }, [output]);

  // Clean up interval on unmount or when streaming stops
  useEffect(() => {
    return () => {
      if (streamingInterval) {
        clearInterval(streamingInterval);
      }
    };
  }, [streamingInterval]);

  return (
    <>
      <style jsx>{`
        @keyframes blink {
          0%, 50% { opacity: 1; }
          51%, 100% { opacity: 0; }
        }
        .animate-blink {
          animation: blink 1s steps(2, start) infinite;
        }
        .scrollbar-thin::-webkit-scrollbar {
          width: 6px;
        }
        .scrollbar-thin::-webkit-scrollbar-track {
          background: #1a1a1a;
        }
        .scrollbar-thin::-webkit-scrollbar-thumb {
          background-color: #3a3a3a;
          border-radius: 3px;
        }
      `}</style>
      
      <div className="flex h-screen w-screen bg-black text-[#e0e0e0] font-mono relative overflow-hidden">
        {/* Side Panel */}
        {sidePanelOpen && (
          <div className="w-64 bg-gray-900/50 backdrop-blur-sm border-r border-gray-700 p-4 overflow-y-auto">
            <h2 className="text-xl font-bold mb-4 text-[#60a5fa]">Command History</h2>
            <ul className="space-y-2">
              {history.map((cmd, index) => (
                <li 
                  key={index} 
                  className="px-2 py-1 rounded hover:bg-gray-800/50 cursor-pointer text-sm"
                  onClick={() => {
                    setInputValue(cmd);
                    setHistoryIndex(-1);
                  }}
                >
                  {cmd}
                </li>
              ))}
            </ul>
          </div>
        )}
        
        {/* Main Terminal */}
        <div className="flex-1 flex flex-col relative">
          {/* Top Bar */}
          <div className="flex items-center px-4 py-3 bg-gray-900/50 backdrop-blur-sm border-b border-gray-700">
            <div className="flex items-center space-x-3">
              <div className="h-6 w-6 bg-gradient-to-r from-blue-500 to-purple-500 rounded"></div>
              <span className="font-bold text-xl">Narad AI</span>
            </div>
            <div className="ml-4 flex items-center space-x-3 text-sm text-gray-400">
              <div className="flex items-center">
                <div className="h-2 w-2 bg-green-500 rounded-full"></span>
                <span>API Connected</span>
              </div>
              <div className="flex items-center">
                <div className="h-2 w-2 bg-blue-500 rounded-full"></span>
                <span>Model: Claude 3</span>
              </div>
            </div>
            <div className="ml-auto">
              <button
                onClick={() => setSidePanelOpen(!sidePanelOpen)}
                className="p-2 rounded hover:bg-gray-800/50 transition-colors text-[#60a5fa]"
              >
                {sidePanelOpen ? '❮' : '❯'}
              </button>
            </div>
          </div>

          {/* Terminal Output */}
          <div
            ref={outputRef}
            className="flex-1 overflow-y-auto p-4 pb-10 scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-gray-700"
          >
            {output.map((line, index) => {
              switch (line.type) {
                case 'output':
                  return <div key={index} className="mb-2">{line.content}</div>;
                case 'input':
                  return <div key={index} className="mb-2">> {line.content}</div>;
                case 'code':
                  return (
                    <div key={index} className="mb-4 p-3 bg-gray-900 rounded overflow-auto">
                      <pre className="text-sm">{line.content}</pre>
                    </div>
                  );
                case 'streaming':
                  return <div key={index} className="mb-2">> {line.content}</div>;
                default:
                  return null;
              }
            })}
          </div>

          {/* Input Line */}
          <div className="absolute bottom-0 left-0 right-0 px-4 py-3 flex items-center bg-gray-900/50 backdrop-blur-sm border-t border-gray-700">
            <span className="mr-2 text-[#60a5fa]">></span>
            <input
              type="text"
              value={inputValue}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              className="flex-1 bg-transparent text-white outline-none placeholder-gray-500"
              placeholder="Type a command..."
              disabled={isStreaming}
            />
            {!isStreaming && (
              <span className="ml-1 h-5 w-0.5 bg-white animate-blink"></span>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default AITerminal;